<?php
/**
 * Tech265 – PayChangu Payment Gateway
 * Central Configuration
 *
 * Load order:
 *   1. src/EnvLoader.php  – parses .env into getenv() / $_ENV
 *   2. Constants defined here using EnvLoader::get/bool/int/arr helpers
 *
 * To change any setting, edit .env — do not edit this file directly.
 */

// ── Bootstrap: load .env ─────────────────────────────────────
require_once __DIR__ . '/../src/EnvLoader.php';

EnvLoader::load(__DIR__ . '/../.env');

// ── In production, assert that critical keys are configured ──
// Uncomment the block below once you have filled in your .env:
//
// if (EnvLoader::get('APP_ENV') === 'production') {
//     EnvLoader::require([
//         'PAYCHANGU_SECRET_KEY',
//         'PAYCHANGU_PUBLIC_KEY',
//         'TECH265_API_KEY',
//         'TECH265_RO_KEY',
//         'TECH265_WH_KEY',
//         'DB_PASS',
//     ]);
// }


// ════════════════════════════════════════════════════════════
// APPLICATION
// ════════════════════════════════════════════════════════════

define('APP_ENV',     EnvLoader::get('APP_ENV',     'development'));
define('APP_NAME',    EnvLoader::get('APP_NAME',    'Tech265 Payments'));
define('APP_VERSION', EnvLoader::get('APP_VERSION', '1.0.0'));
define('APP_URL',     rtrim(EnvLoader::get('APP_URL', 'http://localhost/tech265-payment'), '/'));
define('APP_DEBUG',   EnvLoader::bool('APP_DEBUG',  APP_ENV !== 'production'));


// ════════════════════════════════════════════════════════════
// PAYCHANGU API
// ════════════════════════════════════════════════════════════

define('PAYCHANGU_SECRET_KEY', EnvLoader::get('PAYCHANGU_SECRET_KEY', 'SEC-Su6x4gJ01Scjblzx7LzzPi0LcDhZq4SN'));
define('PAYCHANGU_PUBLIC_KEY', EnvLoader::get('PAYCHANGU_PUBLIC_KEY', 'PUB-nBJzAVzXkSCxZUUT5vtNy9F7CTzYlLL1'));
define('PAYCHANGU_API_BASE',   EnvLoader::get('PAYCHANGU_API_BASE',   'https://api.paychangu.com'));
define('PAYCHANGU_TIMEOUT',    EnvLoader::int('PAYCHANGU_TIMEOUT',    30));

// Callback / Return URLs — auto-built from APP_URL unless overridden in .env
$_cb = EnvLoader::get('PAYCHANGU_CALLBACK_URL');
$_rt = EnvLoader::get('PAYCHANGU_RETURN_URL');
define('PAYCHANGU_CALLBACK_URL', $_cb ?: APP_URL . '/api/v1/payments/callback');
define('PAYCHANGU_RETURN_URL',   $_rt ?: APP_URL . '/api/v1/payments/return');
unset($_cb, $_rt);


// ════════════════════════════════════════════════════════════
// DATABASE
// ════════════════════════════════════════════════════════════

define('DB_HOST',    EnvLoader::get('DB_HOST',    '127.0.0.1'));
define('DB_PORT',    EnvLoader::get('DB_PORT',    '3306'));
define('DB_NAME',    EnvLoader::get('DB_NAME',    'tech265_payments'));
define('DB_USER',    EnvLoader::get('DB_USER',    'root'));
define('DB_PASS',    EnvLoader::get('DB_PASS',    ''));
define('DB_CHARSET', EnvLoader::get('DB_CHARSET', 'utf8mb4'));


// ════════════════════════════════════════════════════════════
// ADMIN PANEL
// ════════════════════════════════════════════════════════════

define('ADMIN_SESSION_LIFETIME', EnvLoader::int('ADMIN_SESSION_LIFETIME', 7200));
define('ADMIN_SESSION_NAME',     EnvLoader::get('ADMIN_SESSION_NAME',     'tech265_admin'));


// ════════════════════════════════════════════════════════════
// LOGGING
// ════════════════════════════════════════════════════════════

// LOG_DIR: absolute path resolved from project root
$_logDir = EnvLoader::get('LOG_DIR', 'logs');
if (!str_starts_with($_logDir, '/') && !preg_match('/^[A-Z]:\\\\/i', $_logDir)) {
    // Relative path — resolve from project root (one level above /config)
    $_logDir = __DIR__ . '/../' . $_logDir;
}
define('LOG_DIR',   realpath($_logDir) ?: __DIR__ . '/../logs');
define('LOG_LEVEL', EnvLoader::get('LOG_LEVEL', APP_DEBUG ? 'debug' : 'error'));
unset($_logDir);


// ════════════════════════════════════════════════════════════
// API AUTHENTICATION
// ════════════════════════════════════════════════════════════

define('API_KEY_HEADER', 'X-API-Key');

// Build the API key map from .env values
// Each entry:  'raw_key_value' => ['name' => '...', 'role' => '...']
$_apiKeys = [];

$_k1 = EnvLoader::get('TECH265_API_KEY', 'tech265-dev-key-CHANGE-ME');
$_k2 = EnvLoader::get('TECH265_RO_KEY',  'tech265-readonly-CHANGE-ME');
$_k3 = EnvLoader::get('TECH265_WH_KEY',  'tech265-webhook-CHANGE-ME');

if ($_k1) $_apiKeys[$_k1] = ['name' => 'Default App Key', 'role' => 'full'];
if ($_k2) $_apiKeys[$_k2] = ['name' => 'Read-Only Key',   'role' => 'readonly'];
if ($_k3) $_apiKeys[$_k3] = ['name' => 'Webhook Key',     'role' => 'webhook'];

define('API_KEYS', $_apiKeys);
unset($_apiKeys, $_k1, $_k2, $_k3);


// ════════════════════════════════════════════════════════════
// RATE LIMITING
// ════════════════════════════════════════════════════════════

define('RATE_LIMIT_ENABLED', EnvLoader::bool('RATE_LIMIT_ENABLED', true));
define('RATE_LIMIT_RPM',     EnvLoader::int('RATE_LIMIT_RPM',     60));


// ════════════════════════════════════════════════════════════
// ALLOWED CURRENCIES
// ════════════════════════════════════════════════════════════

define('ALLOWED_CURRENCIES', EnvLoader::arr('ALLOWED_CURRENCIES', ['MWK', 'USD']));


// ════════════════════════════════════════════════════════════
// DIRECT CHARGE / PAYOUT
// ════════════════════════════════════════════════════════════

// Prefix for auto-generated charge IDs (e.g. PC-T265-XXXXXXXX)
define('CHARGE_ID_PREFIX', EnvLoader::get('CHARGE_ID_PREFIX', 'PC-T265'));
